name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python_version:
          - '3.5'
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
          - '>=3.6'  # https://github.com/jurplel/install-qt-action/blob/3121d3d574d4f4115a03397ad4a97e38b08deb0c/src/main.ts#L12

    runs-on: windows-latest

    steps:  
      - run: |
          python --version

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
          architecture: 'x64'

      - run: |
          python --version

      - run: |
          Get-ChildItem 'Env:\'

      - if: true
        run: |
          'VSCMD_ARG_TGT_ARCH=x86' | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          
      - run: |
          Get-ChildItem 'Env:\'

      - run: |
          python -c "import distutils.util
          print(distutils.util.get_platform())"

      - run: |
          python -m pip install py7zr==0.14.0
