name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        VSCMD_ARG_TGT_ARCH: ['', 'x86', 'x64', 'x299', 'b450']

    runs-on: windows-latest

    steps:  
      - run: |
          python --version

      - run: |
          Get-ChildItem 'Env:\'

      - if: true
        run: |
          'VSCMD_ARG_TGT_ARCH=${{ matrix.VSCMD_ARG_TGT_ARCH }}' | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          
      - run: |
          Get-ChildItem 'Env:\'
          python -c "import distutils.util
          print(distutils.util.get_platform())"

      - run: |
          python -m pip install py7zr==0.14.0
