name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        qt_version: [5.14.2]
        platform: [windows-latest]
        arch: [x86, x64]
        include:
          - platform: windows-latest
            arch: x86
            qtarch: win32_msvc2017
          - platform: windows-latest
            arch: x64
            qtarch: win64_msvc2017_64

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checking out sources
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
  
      - run: |
          Get-ChildItem 'Env:\' | FL

      - run: |
          Get-Command 'python' | FL
          python --version

      - name: Install MSVC compiler
        uses: ilammy/msvc-dev-cmd@v1.7.0
        with:
          # 14.1 is for vs2017, 14.2 is vs2019, following the upstream vcpkg build from Qv2ray-deps repo
          toolset: 14.2
          arch: ${{ matrix.arch }}
  
      - run: |
          Get-ChildItem 'Env:\' | FL

      - run: |
          Get-Command 'python' | FL
          python --version

      - run: |
          "Platform=" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
  
      - run: |
          Get-ChildItem 'Env:\' | FL

      - name: Installing Qt - ${{ matrix.arch }}
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_version }}
          arch: ${{ matrix.qtarch }}
