name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:  
      - run: |
          ${Env:\Platform}

      - run: |
          pip install py7zr==0.14.0
          pip uninstall -y py7zr

      - run: |
          'Platform=x86' | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - run: |
          ${Env:\Platform}

      - run: |
          pip install py7zr==0.14.0
          pip uninstall -y py7zr

      - run: |
          'Platform=x64' | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - run: |
          ${Env:\Platform}

      - run: |
          pip install py7zr==0.14.0
          pip uninstall -y py7zr

      - run: |
          'Platform=x299' | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - run: |
          ${Env:\Platform}

      - run: |
          pip install py7zr==0.14.0
          pip uninstall -y py7zr

      - run: |
          'Platform=' | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - run: |
          ${Env:\Platform}

      - run: |
          pip install py7zr==0.14.0
          pip uninstall -y py7zr
