name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:  
      - run: |
          Get-Item 'Env:\Platform' | FL

      - run: |
          pip install py7zr
          pip uninstall -y py7zr

      - run: |
          'Platform=x86' | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - run: |
          Get-Item 'Env:\Platform' | FL

      - run: |
          pip install py7zr
          pip uninstall -y py7zr

      - run: |
          'Platform=x64' | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - run: |
          Get-Item 'Env:\Platform' | FL

      - run: |
          pip install py7zr
          pip uninstall -y py7zr

      - run: |
          'Platform=x299' | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - run: |
          Get-Item 'Env:\Platform' | FL

      - run: |
          pip install py7zr
          pip uninstall -y py7zr

      - run: |
          'Platform=' | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - run: |
          Get-Item 'Env:\Platform' | FL

      - run: |
          pip install py7zr
          pip uninstall -y py7zr
