name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        qt_version: [5.14.2]
        arch: [x86, x64]
        include:
          - arch: x86
            qtarch: win32_msvc2017
          - arch: x64
            qtarch: win64_msvc2017_64

    runs-on: windows-latest

    steps:  
      - run: |
          Get-ChildItem 'Env:\'

      - name: Install MSVC compiler
        uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14.2
          arch: ${{ matrix.arch }}

      - run: |
          Get-ChildItem 'Env:\'

      - uses: jurplel/install-qt-action@v2
        with:
          version: 5.14.2
          arch: win32_msvc2017
          target: desktop
          install-deps: true
          setup-python: true
          set-env: true
          tools-only: false
          aqtversion: ==1.1.3
          py7zrversion: ==0.14.0

