name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform:
          - ''  # don't modify
          - 'Platform=x86'
          - 'Platform=x64'
          - 'Platform=x299'
          - 'Platform='

    steps:  
      - run: |
          '${{ matrix.platform }}' | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - run: |
          ${Env:\Platform}

      - run: |
          pip install py7zr==0.14.0
