name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: jurplel/install-qt-action@v2
        with:
          version: 5.14.2
          arch: win32_msvc2017
          target: desktop
          install-deps: true
          setup-python: true
          set-env: true
          tools-only: false
          aqtversion: ==1.1.3
          py7zrversion: ==0.14.0
