name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform:
          - ''  # don't modify
          - 'Platform=x86'
          - 'Platform=x64'
          - 'Platform=x299'
          - 'Platform='

    steps:  
      - run: |
          '${{ matrix.platform }}' | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - run: |
          ${Env:\Platform}

      - uses: jurplel/install-qt-action@v2
        with:
          version: 5.14.2
          arch: win32_msvc2017
          target: desktop
          install-deps: true
          setup-python: true
          set-env: true
          tools-only: false
          aqtversion: ==1.1.3
          py7zrversion: ==0.14.0

