name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        arch: [x86, x64]
        include:
          - arch: x86
            qtarch: win32_msvc2017
          - arch: x64
            qtarch: win64_msvc2017_64

    runs-on: windows-latest

    steps:  
      - run: |
          Get-ChildItem 'Env:\'

      - name: Install MSVC compiler
        uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14.2
          arch: ${{ matrix.arch }}

      - run: |
          Get-ChildItem 'Env:\'

      - if: true
        run: |
          'VSCMD_ARG_app_plat=' | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - if: false
        run: |
          'VSCMD_ARG_HOST_ARCH=' | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - run: |
          'VSCMD_ARG_TGT_ARCH=' | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          'VSCMD_ARG_VCVARS_VER=' | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          'VSCMD_VER=' | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          
      - run: |
          Get-ChildItem 'Env:\'

      - name: Installing Qt - ${{ matrix.arch }}
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.14.2'
          arch: ${{ matrix.qtarch }}
